### ISSUE TITLE
Diacritics marks fixes

### ISSUE THREAD

**Issue by vv-monsalve** [skugiz/liter#2]
The following Fail is reported for the font

<details>
    <summary>🔥 <b>FAIL</b> Shapes languages in all GF glyphsets. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/googlefonts.glyphset.html#"></a></summary>
    <div>
* 🔥 **FAIL** <p>GF_Latin_Core glyphset:</p>
<table>
<thead>
<tr>
<th align="left">Language</th>
<th align="left">FAIL messages</th>
</tr>
</thead>
<tbody>
<tr>
<td align="left">nl_Latn (Dutch)</td>
<td align="left">Shaper didn't attach acutecomb to J</td>
</tr>
</tbody>
</table>
 [code: failed-language-shaping]
</div>
</details>

<img width="352" alt="Screenshot 2024-09-17 at 17 03 03" src="https://github.com/user-attachments/assets/c2e90628-d6bc-46be-a54b-e3d651a708c7">

Please add the anchors to both base and diacritic marks glyphs to ensure consistency for the composite glyphs (preventing the below image case); the composition on the fly, as well as to solve related issues, like the below Warns

<img width="703" alt="Screenshot 2024-09-17 at 17 03 21" src="https://github.com/user-attachments/assets/5575e0d5-2a16-4506-9be1-367cd77b5657">

<details>
    <summary>⚠️ <b>WARN</b> Check accent of Lcaron, dcaron, lcaron, tcaron <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/universal.html#"></a></summary>
    <div>
* ⚠️ **WARN** <p>dcaron is decomposed and therefore could not be checked. Please check manually.</p>
 [code: decomposed-outline]
</div>
</details>

<details>
    <summary>⚠️ <b>WARN</b> Ensure soft_dotted characters lose their dot when combined with marks that replace the dot. <a href="https://fontbakery.readthedocs.io/en/stable/fontbakery/checks/shaping.html#"></a></summary>
    <div>
* ⚠️ **WARN** <p>The dot of soft dotted characters <em>should</em> disappear in other cases, for example: i̒ i̦̒ i̧̒ i̵̒ i̶̒ i̷̒ i̸̒ j̒ j̦̒ j̧̒ j̵̒ j̶̒ j̷̒ j̸̒ į̒ į̦̒ į̧̒ į̵̒ į̶̒ į̷̒</p>
<p>Your font fully covers the following languages that require the soft-dotted feature: Ukrainian (Cyrl, 29,273,587 speakers), Lithuanian (Latn, 2,357,094 speakers), Belarusian (Cyrl, 10,064,517 speakers).</p>
<p>Your font does <em>not</em> cover the following languages that require the soft-dotted feature: Koonzime (Latn, 40,000 speakers), Avokaya (Latn, 100,000 speakers), Dutch (Latn, 31,709,104 speakers), Nzakara (Latn, 50,000 speakers), Nateni (Latn, 100,000 speakers), Yala (Latn, 200,000 speakers), South Central Banda (Latn, 244,000 speakers), Mfumte (Latn, 79,000 speakers), Ebira (Latn, 2,200,000 speakers), Dan (Latn, 1,099,244 speakers), Vute (Latn, 21,000 speakers), Cicipu (Latn, 44,000 speakers), Kpelle, Guinea (Latn, 622,000 speakers), Basaa (Latn, 332,940 speakers), Ejagham (Latn, 120,000 speakers), Ma’di (Latn, 584,000 speakers), Fur (Latn, 1,230,163 speakers), Zapotec (Latn, 490,000 speakers), Sar (Latn, 500,000 speakers), Kom (Latn, 360,685 speakers), Mango (Latn, 77,000 speakers), Makaa (Latn, 221,000 speakers), Igbo (Latn, 27,823,640 speakers), Southern Kisi (Latn, 360,000 speakers), Ekpeye (Latn, 226,000 speakers), Bafut (Latn, 158,146 speakers), Navajo (Latn, 166,319 speakers), Lugbara (Latn, 2,200,000 speakers), Dii (Latn, 71,000 speakers), Aghem (Latn, 38,843 speakers), Gulay (Latn, 250,478 speakers), Ijo, Southeast (Latn, 2,471,000 speakers), Mundani (Latn, 34,000 speakers), Bete-Bendi (Latn, 100,000 speakers), Ngbaka (Latn, 1,020,000 speakers).</p>
 [code: soft-dotted]
</div>
</details>

To gain more context on this, you can read the [Diacritics Glyphs tutorial](https://glyphsapp.com/learn/diacritics) and our [Diacitics requirements](https://googlefonts.github.io/gf-guide/diacritics.html).

**Comment by vv-monsalve** [comment]
The legacy marks should be centered in the bounding box.


<img width="552" alt="Screenshot 2024-09-17 at 18 30 55" src="https://github.com/user-attachments/assets/5168e1e5-668b-421f-a6d1-34c66e921b79">

**Comment by skugiz** [comment]
@vv-monsalve fixed a) There is no more error in the «Fontbakery» [report](https://skugiz.github.io/liter/fontbakery/fontbakery-report.html) b) I also checked that everything works correctly in [Figma](ttps://github.com/user-attachments/assets/4bfe50d8-846a-499f-be95-c71b0735b54d)/[Adobe](https://github.com/user-attachments/assets/9c1003f3-1c9d-4c22-a5ba-4fe2a1124d07)

**Comment by vv-monsalve** [comment]
Solved in the source file at commit `c6cb3c5`.
