### ISSUE TITLE
Outlines Quality

### ISSUE THREAD

**Issue by vv-monsalve** [skugiz/liter#4]
Some nodes or handles have a 1-unit difference. Please review all the glyphs and ensure the nodes and handles potion for a well vertical an horizontal placement.

<img width="548" alt="Screenshot 2024-09-17 at 17 08 01" src="https://github.com/user-attachments/assets/743565dd-b033-403a-b0b3-c11252a6a2d6">
<img width="507" alt="Screenshot 2024-09-17 at 18 26 16" src="https://github.com/user-attachments/assets/5ca71c48-cf2f-4fc9-bcee-a6045768a51e">

You can install the `Show Angled Handles` plugin from the Plugin Manager, which will help you spotlight these issues.

<img width="672" alt="Screenshot 2024-09-17 at 18 26 58" src="https://github.com/user-attachments/assets/63bace23-c12e-4dd1-9c1e-2f670131ada2">

**Comment by vv-monsalve** [comment]
Please do not use nested or transformed components to prevent rendering issues.
Please find more details about this in the [Outlies Quality section](https://googlefonts.github.io/gf-guide/outlines.html) of the GF-Guide.

<img width="578" alt="Screenshot 2024-09-17 at 18 34 02" src="https://github.com/user-attachments/assets/77d8ddbf-fdec-41d2-b78b-59a8729b9470">

<img width="524" alt="Screenshot 2024-09-17 at 18 33 13" src="https://github.com/user-attachments/assets/9e1f405c-1ed7-4e66-8b53-832c5b993818">

**Comment by vv-monsalve** [comment]
Inspect the path's direction is okay to prevent undesired holes. E.g. the `ogonek` 

<img width="538" alt="Screenshot 2024-09-17 at 18 36 35" src="https://github.com/user-attachments/assets/0b38d824-04c8-4e4c-9010-7fa6662a627f">

**Comment by skugiz** [comment]
fixed

**Comment by vv-monsalve** [comment]
Solved in the source file at commit c6cb3c5.
